name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
  - name: Set API_KEY
    with:
      credentials: ${{ secrets.AZURE_CREDENTIALS }}
    env: 
      credentials: ${{ secrets.AZURE_CREDENTIALS }}
