name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Build and deploy
      working-directory: ./image-generate-ai
      run: npm run deploy
      env:
        token: ${{ secrets.API_TOKEN }}
