name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

steps:
  - name: Sample Azure action
    with: # Set Azure credentials secret as an input
      API_TOKEN:  ${{ secrets.API_TOKEN }}
    env: # Or as an environment variable
      API_TOKEN:  ${{ secrets.API_TOKEN }}