name: Your Workflow Name

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  your-job-name:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use API Key
        run: echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV

      - name: Run your script
        run: |
          npm install
          npm run build
